version: 0.2

phases:
  install:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/client
  build:
    commands:
      - docker build -t my-portfolio-app-ecr:latest .
  post_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin your_account_id.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker tag my-portfolio-app-ecr:latest your_account_id.dkr.ecr.ap-northeast-1.amazonaws.com/my-portfolio-app-ecr:latest
      - docker push your_account_id.dkr.ecr.ap-northeast-1.amazonaws.com/my-portfolio-app-ecr:latest